"""dashboard: genes, fenotipos, epidemiologia, clasificacion

Revision ID: 17be4b438c90
Revises: f9df89f2c6c2
Create Date: 2026-07-15 19:15:51.048290
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '17be4b438c90'
down_revision: Union[str, None] = 'f9df89f2c6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gene_type', sa.String(length=64), nullable=True),
    sa.Column('hgnc_id', sa.String(length=32), nullable=True),
    sa.Column('ensembl_id', sa.String(length=32), nullable=True),
    sa.Column('uniprot_id', sa.String(length=32), nullable=True),
    sa.Column('omim_id', sa.String(length=16), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_gene_symbol', 'gene', ['symbol'], unique=False)
    op.create_table('phenotype',
    sa.Column('hpo_id', sa.String(length=16), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('hpo_id')
    )
    op.create_table('classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orpha_root', sa.String(length=16), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orpha_root', 'lang', name='uq_classification')
    )
    op.create_table('disease_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('attr_type', sa.String(length=32), nullable=False),
    sa.Column('orphanet_attr_id', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'lang', 'attr_type', 'orphanet_attr_id', name='uq_disease_attribute')
    )
    op.create_index(op.f('ix_disease_attribute_disease_id'), 'disease_attribute', ['disease_id'], unique=False)
    op.create_index(op.f('ix_disease_attribute_lang'), 'disease_attribute', ['lang'], unique=False)
    op.create_table('disease_gene',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=128), nullable=True),
    sa.Column('association_status', sa.String(length=64), nullable=True),
    sa.Column('source_pmids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'gene_id', name='uq_disease_gene')
    )
    op.create_index(op.f('ix_disease_gene_disease_id'), 'disease_gene', ['disease_id'], unique=False)
    op.create_index(op.f('ix_disease_gene_gene_id'), 'disease_gene', ['gene_id'], unique=False)
    op.create_table('disease_phenotype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('hpo_id', sa.String(length=16), nullable=False),
    sa.Column('frequency_id', sa.String(length=16), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('diagnostic_criteria', sa.String(length=64), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hpo_id'], ['phenotype.hpo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'hpo_id', name='uq_disease_phenotype')
    )
    op.create_index(op.f('ix_disease_phenotype_disease_id'), 'disease_phenotype', ['disease_id'], unique=False)
    op.create_index(op.f('ix_disease_phenotype_hpo_id'), 'disease_phenotype', ['hpo_id'], unique=False)
    op.create_index('ix_disease_phenotype_rank', 'disease_phenotype', ['disease_id', 'frequency_rank'], unique=False)
    op.create_table('epidemiology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('orphanet_prevalence_id', sa.String(length=16), nullable=False),
    sa.Column('prevalence_type', sa.String(length=64), nullable=True),
    sa.Column('prevalence_qualification', sa.String(length=64), nullable=True),
    sa.Column('prevalence_class', sa.String(length=64), nullable=True),
    sa.Column('val_moy', sa.String(length=32), nullable=True),
    sa.Column('geographic_area', sa.String(length=128), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orphanet_prevalence_id', 'lang', name='uq_epidemiology')
    )
    op.create_index(op.f('ix_epidemiology_disease_id'), 'epidemiology', ['disease_id'], unique=False)
    op.create_index('ix_epidemiology_geo', 'epidemiology', ['geographic_area'], unique=False)
    op.create_index(op.f('ix_epidemiology_lang'), 'epidemiology', ['lang'], unique=False)
    op.create_table('phenotype_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hpo_id', sa.String(length=16), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('translation_status', sa.String(length=32), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hpo_id'], ['phenotype.hpo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hpo_id', 'lang', name='uq_phenotype_label')
    )
    op.create_index(op.f('ix_phenotype_label_hpo_id'), 'phenotype_label', ['hpo_id'], unique=False)
    op.create_index(op.f('ix_phenotype_label_lang'), 'phenotype_label', ['lang'], unique=False)
    op.create_table('classification_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('parent_orpha', sa.String(length=16), nullable=True),
    sa.Column('child_orpha', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification_id', 'parent_orpha', 'child_orpha', name='uq_classification_edge')
    )
    op.create_index(op.f('ix_classification_edge_child_orpha'), 'classification_edge', ['child_orpha'], unique=False)
    op.create_index(op.f('ix_classification_edge_classification_id'), 'classification_edge', ['classification_id'], unique=False)
    op.create_index(op.f('ix_classification_edge_parent_orpha'), 'classification_edge', ['parent_orpha'], unique=False)
    op.drop_index(op.f('ix_disease_label_trgm'), table_name='disease_label', postgresql_ops={'mr_unaccent(lower(label))': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_disease_label_trgm'), 'disease_label', [sa.literal_column('mr_unaccent(lower(label))')], unique=False, postgresql_ops={'mr_unaccent(lower(label))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_classification_edge_parent_orpha'), table_name='classification_edge')
    op.drop_index(op.f('ix_classification_edge_classification_id'), table_name='classification_edge')
    op.drop_index(op.f('ix_classification_edge_child_orpha'), table_name='classification_edge')
    op.drop_table('classification_edge')
    op.drop_index(op.f('ix_phenotype_label_lang'), table_name='phenotype_label')
    op.drop_index(op.f('ix_phenotype_label_hpo_id'), table_name='phenotype_label')
    op.drop_table('phenotype_label')
    op.drop_index(op.f('ix_epidemiology_lang'), table_name='epidemiology')
    op.drop_index('ix_epidemiology_geo', table_name='epidemiology')
    op.drop_index(op.f('ix_epidemiology_disease_id'), table_name='epidemiology')
    op.drop_table('epidemiology')
    op.drop_index('ix_disease_phenotype_rank', table_name='disease_phenotype')
    op.drop_index(op.f('ix_disease_phenotype_hpo_id'), table_name='disease_phenotype')
    op.drop_index(op.f('ix_disease_phenotype_disease_id'), table_name='disease_phenotype')
    op.drop_table('disease_phenotype')
    op.drop_index(op.f('ix_disease_gene_gene_id'), table_name='disease_gene')
    op.drop_index(op.f('ix_disease_gene_disease_id'), table_name='disease_gene')
    op.drop_table('disease_gene')
    op.drop_index(op.f('ix_disease_attribute_lang'), table_name='disease_attribute')
    op.drop_index(op.f('ix_disease_attribute_disease_id'), table_name='disease_attribute')
    op.drop_table('disease_attribute')
    op.drop_table('classification')
    op.drop_table('phenotype')
    op.drop_index('ix_gene_symbol', table_name='gene')
    op.drop_table('gene')
    # ### end Alembic commands ###
