"""ensayos clinicos y farmacos huerfanos

Revision ID: 194f5c3a69c6
Revises: 17be4b438c90
Create Date: 2026-07-15 20:24:57.018514
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '194f5c3a69c6'
down_revision: Union[str, None] = '17be4b438c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orphan_drug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency', sa.String(length=16), nullable=False),
    sa.Column('designation_number', sa.String(length=64), nullable=False),
    sa.Column('medicine_name', sa.Text(), nullable=True),
    sa.Column('active_substance', sa.Text(), nullable=True),
    sa.Column('intended_use', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('designation_date', sa.String(length=16), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency', 'designation_number', name='uq_orphan_drug')
    )
    op.create_index(op.f('ix_orphan_drug_agency'), 'orphan_drug', ['agency'], unique=False)
    op.create_table('trial',
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=True),
    sa.Column('study_type', sa.String(length=32), nullable=True),
    sa.Column('lead_sponsor', sa.Text(), nullable=True),
    sa.Column('sponsor_class', sa.String(length=32), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=16), nullable=True),
    sa.Column('last_update', sa.String(length=16), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nct_id')
    )
    op.create_index(op.f('ix_trial_status'), 'trial', ['status'], unique=False)
    op.create_table('disease_drug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.String(length=16), nullable=False),
    sa.Column('matched_on', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['orphan_drug.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'drug_id', name='uq_disease_drug')
    )
    op.create_index(op.f('ix_disease_drug_disease_id'), 'disease_drug', ['disease_id'], unique=False)
    op.create_table('disease_trial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.String(length=16), nullable=False),
    sa.Column('matched_on', sa.String(length=64), nullable=True),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nct_id'], ['trial.nct_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'nct_id', name='uq_disease_trial')
    )
    op.create_index(op.f('ix_disease_trial_disease_id'), 'disease_trial', ['disease_id'], unique=False)
    op.create_table('trial_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nct_id', sa.String(length=16), nullable=False),
    sa.Column('facility', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['nct_id'], ['trial.nct_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nct_id', 'facility', 'city', name='uq_trial_location')
    )
    op.create_index(op.f('ix_trial_location_country'), 'trial_location', ['country'], unique=False)
    op.create_index(op.f('ix_trial_location_nct_id'), 'trial_location', ['nct_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_location_nct_id'), table_name='trial_location')
    op.drop_index(op.f('ix_trial_location_country'), table_name='trial_location')
    op.drop_table('trial_location')
    op.drop_index(op.f('ix_disease_trial_disease_id'), table_name='disease_trial')
    op.drop_table('disease_trial')
    op.drop_index(op.f('ix_disease_drug_disease_id'), table_name='disease_drug')
    op.drop_table('disease_drug')
    op.drop_index(op.f('ix_trial_status'), table_name='trial')
    op.drop_table('trial')
    op.drop_index(op.f('ix_orphan_drug_agency'), table_name='orphan_drug')
    op.drop_table('orphan_drug')
    # ### end Alembic commands ###
